/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct intpair {
	int a;
	int b;
};
typedef struct intpair intpair;

#define CALC_PROG 0x31234567
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  int * suma_1(intpair *, CLIENT *);
extern  int * suma_1_svc(intpair *, struct svc_req *);
#define RESTA 2
extern  int * resta_1(intpair *, CLIENT *);
extern  int * resta_1_svc(intpair *, struct svc_req *);
#define MULTIPLICA 3
extern  int * multiplica_1(intpair *, CLIENT *);
extern  int * multiplica_1_svc(intpair *, struct svc_req *);
#define DIVIDE 4
extern  float * divide_1(intpair *, CLIENT *);
extern  float * divide_1_svc(intpair *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  int * suma_1();
extern  int * suma_1_svc();
#define RESTA 2
extern  int * resta_1();
extern  int * resta_1_svc();
#define MULTIPLICA 3
extern  int * multiplica_1();
extern  int * multiplica_1_svc();
#define DIVIDE 4
extern  float * divide_1();
extern  float * divide_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_intpair (XDR *, intpair*);

#else /* K&R C */
extern bool_t xdr_intpair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
